name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Roblox/setup-foreman@v1
        name: Install Foreman
        with:
          version: "^1.0.0"
          token: ${{ SECRETS.GITHUB_TOKEN }}

      - run: rojo build -o bsb-build.rbxl

      - name: Publish
        shell: bash
        env:
          UID: 4233760541
          PID: 11963092817
          API_KEY: ${{ secrets.DEVKEY }}
          FILE: bsb-build.rbxl

        run: rbxcloud experience publish -a "$API_KEY" -u "$UID" -p "$PID" -t published -f "$FILE"
